services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD={{ DB_PASSWORD }}
      - POSTGRES_USER={{ DB_USER }}
    ports:
      - 5432:5432
    restart: always
  system-service:
    environment:
    # Server vars
      - SYSTEM_PORT={{ SYSTEM_PORT }}
      - SYSTEM_ENV={{ SYSTEM_ENV }}
      - SYSTEM_KEY_APPLICATION_NAME={{SYSTEM_KEY_APPLICATION_NAME}
      - ENABLE_LOCAL_LOG={{ENABLE_LOCAL_LOG}}
      # other services ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - DATABASE_URL=postgresql://{{ DB_USER }}:{{DB_PASSWORD}}@{{hostIp}}:5432
    image: ghcr.io/bednaz98/{{ repo_name }}:main
    ports:
      - {{ SYSTEM_PORT }}:{{ SYSTEM_PORT }}
    expose:
      - {{ SYSTEM_PORT }}
    restart: always
    depends_on:
      - database